FROM registry.access.redhat.com/ubi8/ubi:latest

MAINTAINER Travis <tmichett@redhat.com>

# Environment variable for Apache Port
ENV PORT 8080

RUN dnf install -y httpd && \
    dnf clean all

# Change configuration of Apache WS to listen on the port specified as an environment variable in the Containerfile

RUN sed -ri -e "/^Listen 80/c\Listen ${PORT}" /etc/httpd/conf/httpd.conf

RUN mkdir /var/www/html/images

# Demo to simulate new image being built from pipeline
# Copy all files under src/ folder to Apache DocumentRoot (/var/www/html)
ADD https://people.redhat.com/~tmichett/OCP/index_html /var/www/html/index.html 
ADD https://people.redhat.com/~tmichett/OCP/rht_training_logo.png /var/www/html/images/

RUN chmod -R +rx /var/www/html

## Needed for OpenShift to Set Permissions
#  Fix filesystem ownership for writing logs
#  Fix filesystem ownership for accessing the runtime PID
#  Prevents need from modifying SCC and creating service accounts
RUN chgrp -R 0 /var/log/httpd /var/run/httpd && \
    chmod -R g=u /var/log/httpd /var/run/httpd

## Needed for OpenShift to set a generic user
USER 1001

# Start Apache in the foreground
CMD ["httpd", "-D", "FOREGROUND"]

