ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:imagesdir: images/
endif::[]


== Managing Containers as System Services

=== Starting Containers Automatically with the Server

*Systemd* user unit files can be created for rootless containers allowing them to be managed with *systemctl* commands similar to regular Linux services. By enabling the services, the associated containers can start when the host machine starts. Furthermore, by running in "rootless" mode the services can be managed from a non-privileged account.

=== Running *Systemd* Services as a Regular User

In addition to managing system services, *SystemD* can also manage user services. Users can create their own unit files for their services which can be managed with *systemctl* without requiring *root* access.

When services are enabled as a user service (non-root user), the service automatically starts when you open your first session. The service will stop when you've closed your last session.

.Forcing User-Enabled Services to Start/Stop with the Server
[TIP]
====
It is possible to change the default behavior of user services (*systemd.units*) by using *loginctl enable-linger* command to override the behavior and enable the *Linger* feature. It can be disabled with *loginctl disable-linger*. It is possible to show the *Linger* status for a user using the *loginctl show-user _username_* command.
====


==== Creating and Managing Systemd User Services

In order to define *systemd* user services, the *~/.config/systemd/user* directory must be created to store the unit files. User *systemd.unit* files have the same syntax as a regular system unit file.

.More Information on SYSTEMD
[NOTE]
====
For more information the *systemd.unit* and *systemd.service* man pages should be used.
====

.User Services with *systemctl*

User services can be controlled with the *systemctl* command. However, the *--user* option must be provided on the command line before the [enable, start, stop, reload] or other options and the service name.

.Using *systemctl --user* Commands
[IMPORTANT]
====
In order for the *systemctl --user* command to function properly, you must be logged in directly as using *sudo* or *su* commands will not work. The *systemctl* command interacts with a per user *systemd --user* process.
====

.Classroom Machines
[cols="4a,4a,4a",options=header]
|===
|SystemD Tasks
|System Services
|User Services

|*Storing custom unit files*
|/etc/systemd/system/unit.service
|~/.config/systemd/user/unit.service



|*Reloading unit files*
|systemctl daemon-reload
|systemctl --user daemon-reload


|*Starting and stopping a service*
|systemctl start UNIT

systemctl stop UNIT
|systemctl --user start UNIT

systemctl --user stop UNIT


|*Starting a service when the machine starts*
|systemctl enable UNIT
|loginctl enable-linger

systemctl --user enable UNIT


|===


==== Managing Containers Using *Systemd* Services

With a single container host, running small number of containers, user-based *systemd* files can be configured to automatically start the containers with the server. For larger and production based systems, Red Hat OpenShift should be used.


===== Creating a Dedicated User Account to Run Containers

To simplify management of rootless containers a dedicated container user account can be created for running all containers.

.A Container User Account
[IMPORTANT]
====
If you are creating a user account for containers, the user account and group should be a regular user account. It cannot be created with the *--system* option as it would then be considered a system account and out of the reserved account IDs for regular user accounts.
====

===== Creating the Systemd Unit File

It is possible to use *podman* to generate the *systemd* unit files. In order to generate a *systemd* unit file, you will use *podman generate systemd* command. This works best when you are in the *~/.config/systemd/user/* directory.


.Generating *systemd* Files with Podman
[IMPORTANT]
====
The *podman generate systemd*  uses a container as a model to create the configuration file, so the container must be deleted after the creation of the *systemd* file as *systemd* expect the container to not already exist.
====

.*podman generate systemd* Command Options

* *--name _ContainerName_* - Specifies name of container to use as a model for generating the unit file. This also defines the name of the container built from the *systemd* unit file.

* *--files* - Instructs Podman to create the unit file in the current directory

* *--new* - Instructs Podman to configure the *systemd* service to create the container when the service starts and delete the container when the service stops. Without the *--new* option, Podman configures the service to start/stop the existing container without deleting it.


===== Starting and Stopping Containers Using Systemd

The *systemctl* command can control containers.

.Avoid using *podman* for SystemD containers
[CAUTION]
====
Containers managed with *systemctl* commands are controlled by *systemd*. *systemd* monitors the container status and restarts if a failure is detected. Never use *podman* to start/stop *systemd* containers.
====

===== Configuring Containers to Start When the Host Machine Starts

By default, *systemd* user services start when a user opens the first session and stops when a users closes the last session on a container host. It is possible to enable the service to start/stop with the server. In order to enable starting/stopping automatically *loginctl enable-linger* must be run.

.Enable Login Linger
[source,bash]
----
loginctl enable-linger
----

.Enable a Container to Start Automatically
[source,bash]
----
systemctl --user enable container-web
----

.Disable a Container to Starting Automatically
[source,bash]
----
systemctl --user disable container-web
----


==== Managing Containers Running as Root with Systemd

It is also possible to configure containers that should be run as *root* to be managed with *SystemD* unit files. The advantage to using containers as services running as root is that they work exactly like normal system unit files.

.Configuring *root* SystemD Container Files

* No dedicated user needed
* When *podman generate systemd* is run, it should be in the */etc/systemd/
system* directory so that the *systemd* unit file is in the correct directory.
* You can use *systemctl* and do not need the *--user* option
* There is no need to enable *Linger* with the *loginctl enable-linger* command.


==== Orchestrating Containers at Scale

Red Hat Training offers other courses, starting with the free technical overview course Deploying Containerized Applications (DO080) and continuing with Introduction to Containers, Kubernetes, and OpenShift (DO180). For more information, visit https://www.redhat.com/training.

A number of resources are available there, including ways to try out OpenShift for yourself using tools like CodeReady Containers [https://developers.redhat.com/products/ codeready-containers/overview]. See https://www.openshift.com/try for more information.

=== DEMO - Managing Containers as Services

.DEMO - Managing Containers as Services
=====

. Create a Container User
+
[source,bash]
----
[root@server ~]# useradd cuser
[root@server ~]# passwd cuser
Changing password for user cuser.
New password: redhat
BAD PASSWORD: The password is shorter than 8 characters
Retype new password: redhat
passwd: all authentication tokens updated successfully
----

. Login to *server* with the *cuser* that was just created
+
[source,bash]
----
[student@workstation ~]$ ssh cuser@servera
Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

[cuser@servera ~]$
----

. Create Directories and Config Files for Container Registry
+
[source,bash]
----
[cuser@server ~]$ mkdir -p ~/.config/containers/

[cuser@server ~]$ cd ~/.config/containers/

[cuser@server containers]$ scp student@workstation:github/OCP_Demos/Containers/labs/SystemD/registries.conf .
----

. Create Content for Webserver
+
[source,bash]
----
[cuser@server ~]$ mkdir -p ~/www/html

[cuser@server ~]$ echo "I am a demo webserver" > ~/www/html/index.html
----

. Login to the container registry
+
[source,bash]
----
[cuser@server ~]$ podman login quay.io
Username: <UN>
Password: <PW>
Login Succeeded!
----

. Create and Run Reference Container
+
[source,bash]
----
[cuser@server ~]$ podman run -d --name demoweb -p 8080:80 -v ~/www:/var/www:Z quay.io/redhattraining/httpd-parent
----

. Verify webserver is running
+
[source,bash]
----
[cuser@server ~]$ curl localhost:8080
I am a demo webserver
----

. Prepare the directory and create a *systemd* unit file
+
[source,bash]
----
[cuser@server ~]$ mkdir -p ~/.config/systemd/user/

[cuser@server ~]$ cd ~/.config/systemd/user/

[cuser@server user]$ podman generate systemd --name demoweb --files --new
/home/cuser/.config/systemd/user/container-demoweb.service
----

. View *systemd* Unit File
+
[source,bash]
----
[cuser@server user]$ cat /home/cuser/.config/systemd/user/container-demoweb.service
# container-demoweb.service
# autogenerated by Podman 3.0.2-dev
# Tue Oct 26 11:22:02 EDT 2021

[Unit]
Description=Podman container-demoweb.service
Documentation=man:podman-generate-systemd(1)
Wants=network.target
After=network-online.target

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=on-failure
TimeoutStopSec=70
ExecStartPre=/bin/rm -f %t/container-demoweb.pid %t/container-demoweb.ctr-id
ExecStart=/usr/bin/podman run --conmon-pidfile %t/container-demoweb.pid --cidfile %t/container-demoweb.ctr-id --cgroups=no-conmon --replace -d --name demoweb -p 8080:80 -v /home/cuser/www:/var/www:Z quay.io/redhattraining/httpd-parent
ExecStop=/usr/bin/podman stop --ignore --cidfile %t/container-demoweb.ctr-id -t 10
ExecStopPost=/usr/bin/podman rm --ignore -f --cidfile %t/container-demoweb.ctr-id
PIDFile=%t/container-demoweb.pid
Type=forking

[Install]
WantedBy=multi-user.target default.target
----

. Remove the Reference Container and Verify
+
[source,bash]
----
[cuser@server user]$ podman rm demoweb -f
c0c418905cb571cbbade303c94486568b3ac87ca3afe72be92a957be421bfcc4

[cuser@server user]$ podman ps -a
CONTAINER ID  IMAGE   COMMAND  CREATED  STATUS  PORTS   NAMES
----

. Use *systemctl* to Start and Enable the Container Service
+
[source,bash]
----
[cuser@server user]$ systemctl --user enable container-demoweb --now
Created symlink /home/cuser/.config/systemd/user/multi-user.target.wants/container-demoweb.service → /home/cuser/.config/systemd/user/container-demoweb.service.
Created symlink /home/cuser/.config/systemd/user/default.target.wants/container-demoweb.service → /home/cuser/.config/systemd/user/container-demoweb.service.
----
+
.SystemD Container Services
[WARNING]
======
Once a containerized application has been provisioned as a SystemD service, it cannot be managed and should not be managed with *podman* instead, the service should be managed with the *user* *_systemctl_* SystemD commands.
======

. Enable *user-linger* so that the service starts when the system boots
+
[source,bash]
----
[cuser@server ~]$ loginctl enable-linger cuser
----
+
.Must Enable User Linger Service
[IMPORTANT]
======
The *enable-linger* will allow SystemD services to start as a user when the system boots. Failure to enable this will result in services being offline until the user logs in for the first time.
======

. Verify Container is Running
+
[source,bash]
----
[cuser@server user]$ curl localhost:8080
I am a demo webserver

[cuser@server user]$ podman ps
CONTAINER ID  IMAGE                                COMMAND               CREATED             STATUS                 PORTS                 NAMES
6da1c129c3e2  quay.io/redhattraining/httpd-parent  /bin/sh -c /usr/s...  About a minute ago  Up About a minute ago  0.0.0.0:8080->80/tcp  demoweb
----

. Reboot the server
+
[source,bash]
----
[cuser@server user]$ su -
Password:
Last login: Fri Nov  5 16:12:41 EDT 2021 from 172.25.250.9 on pts/0

[root@server ~]# reboot
----

. Log back into the server as any user other than *cuser*
+
[source,bash]
----
[student@workstation Buildah]$ ssh root@server
----

. Verify Status of Website
+
[source,bash]
----
[root@server ~]# curl localhost:8080
I am a demo webserver
----

. Verify that Container isn't running as root
+
[source,bash]
----
[root@server ~]# podman ps -a
CONTAINER ID  IMAGE   COMMAND  CREATED  STATUS  PORTS   NAMES
----


=====

.References
[NOTE]
====

*Managing containerized system services with Podman*: https://developers.redhat.com/blog/2018/11/29/managing-containerized-system-services-with-podman

*Improved systemd integration with Podman 2.0*: https://www.redhat.com/sysadmin/improved-systemd-podman

*RH134 Course - Section 13.11: Managing Containers as Services*: https://rol.redhat.com/rol/app/courses/rh134-8.2/pages/ch13s11

*podman generate systemd*:https://docs.podman.io/en/latest/markdown/podman-generate-systemd.1.html

*podman auto-update*: https://github.com/containers/podman/blob/v2.0/docs/source/markdown/podman-auto-update.1.md

*Running containers with Podman and shareable systemd services*: https://www.redhat.com/sysadmin/podman-shareable-systemd-services

*How I learned to stop worrying and love systemd*: https://www.redhat.com/sysadmin/love-systemd

*Mastering systemd: Securing and sandboxing applications and services*: https://www.redhat.com/sysadmin/mastering-systemd

*man pages*: _podman-generate-systemd_, _podman-auto-update_
====
