ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:imagesdir: images/
endif::[]


=== Setup Exercise

Before you begin using the customized DO180 Workshop Lab Environment a couple things must be accomplished.

.Before you Begin
. Prepare Workstation
. SSH Keys must be Generated and Distributed for the root user on *server*
. Github Projects Must be Downloaded
. Ansible Playbooks Must be Executed

There will be two Github projects used in this course for the custom exercises and demonstrations.

* *OCP Demos*: https://github.com/tmichett/OCP_Demos - The */Containers* directory contains most of the resources being used for the course.
* *Quay_Lab_PoC*: https://github.com/tmichett/quay_lab_poc - This repository contains playbooks that will setup and deploy Quay locally on the *server* system.

The lab environment will need *server* configured to be our *quay.local* system and will need to have access to all packages and keys.

.Lab Installation and Setup Exercise
====

. Create Directories and Download Github Repos
+
.Creating Directory and Switch to Directory
[source,bash]
----
[student@workstation ~]$ mkdir github ; cd github
----
+
.Cloning Repositories - Cloning *quay_lab_poc*
[source,bash]
----
[student@workstation github]$ git clone https://github.com/tmichett/quay_lab_poc.git
Cloning into 'quay_lab_poc'...
remote: Enumerating objects: 266, done.
remote: Counting objects: 100% (266/266), done.
remote: Compressing objects: 100% (167/167), done.
remote: Total 266 (delta 67), reused 253 (delta 54), pack-reused 0
Receiving objects: 100% (266/266), 5.90 MiB | 22.90 MiB/s, done.
Resolving deltas: 100% (67/67), done
----
+
.Cloning Repositories - Cloning *OCP_Demos*
[source,bash]
----
[student@workstation github]$ git clone https://github.com/tmichett/OCP_Demos.git
Cloning into 'OCP_Demos'...
remote: Enumerating objects: 763, done.
remote: Counting objects: 100% (763/763), done.
remote: Compressing objects: 100% (527/527), done.
remote: Total 763 (delta 329), reused 595 (delta 181), pack-reused 0
Receiving objects: 100% (763/763), 37.16 MiB | 29.22 MiB/s, done.
Resolving deltas: 100% (329/329), done.
----

. Switch to the *OCP_Demos/Containers/labs/server_prep* Folder
+
[source,bash]
----
[student@workstation github]$ cd OCP_Demos/Containers/labs/server_prep
----

. Execute the *Setup_Workstation.yml* playbook
+
[source,bash]
----
[student@workstation server_prep]$ ansible-playbook Setup_Workstation.yml
----

. Create SSH keys
+
[source,bash]
----
[student@workstation server_prep]$ ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/home/student/.ssh/id_rsa):
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /home/student/.ssh/id_rsa.
Your public key has been saved in /home/student/.ssh/id_rsa.pub.
The key fingerprint is:
SHA256:/FXYb+9b7dGD9CJpwTdsE0MqJkitLBuHYJDofp4Jz3w student@workstation.lab.example.com
The key's randomart image is:
+---[RSA 3072]----+
|+.   ..      .   |
|oo  . ..    oo   |
|o . o... o ..oo  |
| . + + .o o ..o. |
|.   =   S  o.B  o|
| o o     . .* =.+|
|  B o     .+ o +=|
|   B E    . . .o+|
|    .          .+|
+----[SHA256]-----+
----

. Copy SSH key for the *root* user to *server*
+
[source,bash]
----
[student@workstation server_prep]$ ssh-copy-id root@server
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/student/.ssh/id_rsa.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
root@server's password:

Number of key(s) added: 1

Now try logging into the machine, with:   "ssh 'root@server'"
and check to make sure that only the key(s) you wanted were added.
----

. Execute the *Setup_Server.yml* playbook
+
[source,bash]
----
[student@workstation server_prep]$ ansible-playbook Setup_Server.yml
----
====
