apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-load-limits
  labels:
    app: demo-load-limits
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-load-limits
  template:
    metadata:
      labels:
        app: demo-load-limits
    spec:
      containers:
      - image: registry.ocp4.example.com:8443/redhattraining/long-load:v1
        resources:
          requests:
            memory: 1Gi
        imagePullPolicy: Always
        name: demo-load-limits
        startupProbe:
          failureThreshold: 30
          periodSeconds: 3
          httpGet:
            path: /health
            port: 3000
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 3
          httpGet:
            path: /health
            port: 3000
        env:
        - name: START_DELAY
          value: "0"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: demo-load-limits
  labels:
    app: demo-load-limits
spec:
  selector:
    app: demo-load-limits
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: demo-load-limits
  labels:
    app: demo-load-limits
spec:
  port:
    targetPort: 3000
  to:
    kind: Service
    name: demo-load-limits
